//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneDirectory {
	
	
	public partial class addContact {
		
		protected System.Web.UI.HtmlControls.HtmlForm form;
		
		protected System.Web.UI.HtmlControls.HtmlImage imgpreview;
		
		protected System.Web.UI.HtmlControls.HtmlInputText fname;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rex1;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator req1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText nname;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rex2;
		
		protected System.Web.UI.HtmlControls.HtmlInputText pname;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rex3;
		
		protected System.Web.UI.HtmlControls.HtmlSelect gender;
		
		protected System.Web.UI.HtmlControls.HtmlInputText addr;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rex4;
		
		protected System.Web.UI.HtmlControls.HtmlInputText cname;
		
		protected System.Web.UI.HtmlControls.HtmlInputText post;
		
		protected System.Web.UI.HtmlControls.HtmlInputText phones;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rex5;
		
		protected System.Web.UI.HtmlControls.HtmlInputText mails;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator rex6;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile imgInp;
		
		protected System.Web.UI.WebControls.Button add;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl messagebox;
	}
}
